"""The agents file the dashboard owns.

`config.yaml` is the operator's, comments and all, and nothing here writes to it. The
UI gets its own file instead, so a save cannot reformat a hand-written config or drop
the notes in it -- and so an operator who never opens the dashboard has a config that
no process rewrites behind them.

The two files are merged at load. Where they name the same agent the server refuses to
boot: a precedence rule is how an edit comes to save successfully and do nothing.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

from ..contract import ConfigError

DEFAULT_MANAGED_PATH = Path("~/.orchestrator-mcp/agents.yaml")

HEADER = """\
# Generated by the orchestrator-mcp dashboard.
#
# Safe to hand-edit -- it is validated at boot exactly like config.yaml is -- but the
# next save from the dashboard rewrites this header and sorts the keys.
#
# An agent named both here and in config.yaml is a startup error, not a merge.
"""


def managed_path(block: dict[str, Any]) -> Path:
    """Where the managed file lives, read from the raw block.

    Raw, and not from a parsed `ConsultConfig`, because the agents in this file have to
    be merged in *before* that config can be built.
    """
    raw = block.get("managed_agents_path")
    if raw is None:
        raw = DEFAULT_MANAGED_PATH
    # A blank value is deliberately *not* the default here. `ConsultConfig` turns it
    # into `Path(".")`, and the two disagreeing is how the page ends up reading one
    # file while the boot merged another.
    return Path(os.path.expandvars(str(raw))).expanduser()


def read_managed(path: Path) -> dict[str, Any]:
    """The agent mappings in the managed file. A missing file is no agents, not an
    error: the dashboard has simply never been used here."""
    if not path.exists():
        return {}

    try:
        document = yaml.safe_load(path.read_text()) or {}
    except OSError as exc:
        # A directory, or a file this user cannot open. Both are configuration
        # mistakes, and both arrive here as an `OSError` nothing upstream expects.
        raise ConfigError(f"{path} cannot be read: {exc}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"{path} is not valid YAML: {exc}") from exc

    if not isinstance(document, dict):
        raise ConfigError(f"{path} must be a YAML mapping")

    agents = document.get("agents") or {}
    if not isinstance(agents, dict):
        raise ConfigError(f"`agents:` in {path} must be a mapping of agent id to settings")
    return agents


def write_managed(path: Path, agents: dict[str, Any]) -> None:
    """Replace the managed file atomically.

    Same posture as the consultation store: the file is `0600`, and the directory is
    created `0700`, because an agent entry names a path on this machine and, for
    anyone who edits the default, possibly a private endpoint.

    Created, not enforced. A directory that already exists is left at whatever mode it
    has, because `managed_agents_path` can name any file the operator likes -- its
    parent may be `$HOME`, or a directory holding other things -- and silently
    tightening someone else's directory is a worse surprise than the one the `0600`
    file already covers. The mode of a directory this did not create is theirs.

    A temp file in the same directory and `os.replace` so a reader mid-save sees the
    old file or the new one, never half of either -- the reader here being a server
    starting up while someone clicks Save.
    """
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    body = yaml.safe_dump({"agents": agents}, sort_keys=True, default_flow_style=False)

    handle = tempfile.NamedTemporaryFile(
        "w", dir=path.parent, prefix=f".{path.name}.", suffix=".tmp", delete=False
    )
    try:
        with handle:
            handle.write(HEADER + "\n" + body)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(handle.name, 0o600)
        os.replace(handle.name, path)
    except BaseException:
        Path(handle.name).unlink(missing_ok=True)
        raise
